export default {
    products: [
        {
            _id: "1",
            name: "Beach Shirt",
            category: "Shirts",
            image: "/images/d1.jpg",
            price: 25,
            brand: "Nike",
            rating: 4.1,
            numReviews: 10,
            countInStock: 0,
        },
        {
            _id: "2",
            name: "Plain Shirt",
            category: "Shirts",
            image: "/images/d1.jpg",
            price: 20,
            brand: "Nike",
            rating: 4.3,
            numReviews: 7,
            countInStock: 8,
        },
        {
            _id: "3",
            name: "Party Shirt",
            category: "Shirts",
            image: "/images/d1.jpg",
            price: 45,
            brand: "Nike",
            rating: 4.5,
            numReviews: 5,
            countInStock:4,
        },
        {
            _id: "4",
            name: "Date Shirt",
            category: "Shirts",
            image: "/images/d1.jpg",
            price: 40,
            brand: "Nike",
            rating: 4.4,
            numReviews: 9,
            countInStock: 6,
        },
        {
            _id: "5",
            name: "Acqua T-Shirt",
            category: "Shirts",
            image: "/images/d1.jpg",
            price: 8,
            brand: "Nike",
            rating: 3.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: "6",
            name: "Reggae T-Shirt",
            category: "Shirts",
            image: "/images/d1.jpg",
            price: 10,
            brand: "Nike",
            rating: 3.5,
            numReviews: 8,
            countInStock: 9,
        },
    ],
};
